export const NEW_RESUME = 'NEW_RESUME';
export const FETCH_RESUMES = 'FETCH_RESUMES';
export const NEW_COVER_LETTER = 'NEW_COVER_LETTER';
export const FETCH_COVER_LETTERS = 'FETCH_COVER_LETTERS';
export const NEW_RESUME_PENDING = 'NEW_RESUME_PENDING';
export const FETCH_RESUMES_PENDING = 'FETCH_RESUMES_PENDING';
export const NEW_COVER_LETTER_PENDING = 'NEW_COVER_LETTER_PENDING';
export const FETCH_COVER_LETTERS_PENDING = 'FETCH_COVER_LETTERS_PENDING';
