export const FETCH_JOB_DETAIL = 'FETCH_JOB_DETAIL';
export const FETCH_JOB_DETAIL_PENDING = 'FETCH_JOB_DETAIL_PENDING';
export const UPDATE_JOB_DETAIL = 'UPDATE_JOB_DETAIL';
export const UPDATE_JOB_DETAIL_PENDING = 'UPDATE_JOB_DETAIL_PENDING';
