export const NEW_NOTE = 'NEW_NOTE';
export const NEW_NOTE_PENDING = 'NEW_NOTE_PENDING';
export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_NOTES_PENDING = 'FETCH_NOTES_PENDING';
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_PENDING = 'DELETE_NOTE_PENDING';
